services:
  about:
    image: nginx:alpine
    volumes:
      - ./about:/usr/share/nginx/html
    networks:
      - backend

  myresearch:
    image: nginx:alpine
    volumes:
      - ./myresearch:/usr/share/nginx/html
    networks:
      - backend
  ct519:
    image: nginx:alpine
    volumes:
      - ./ct519:/usr/share/nginx/html
    networks:
      - backend
  landing:
    image: nginx:alpine
    volumes:
      - ./landing:/usr/share/nginx/html
    networks:
      - backend
  reverse_proxy:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - myresearch
      - ct519
      - about
      - landing
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
